config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"

  namespace :admin do
    resources :tags, only: [:index, :create, :edit, :update]
  end
  namespace :admin do
    resources :groups, only: [:index, :show, :destroy]
  end
  namespace :admin do
    resources :end_users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get 'posts' => 'end_users#posts', as: 'posts'
      end
    end
  end
  namespace :admin do
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:destroy]
    end
  end
  namespace :admin do
    resources :contacts, only: [:show, :update]
  end
  namespace :admin do
    root to: "homes#top"
  end
  namespace :public do
    resources :groups, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resource :group_users, only: [:create, :destroy]
    end
  end
  namespace :public do
    resources :group_chats, only: [:show, :create]
  end
  namespace :public do
    resources :chats, only: [:show, :create]
  end
  namespace :public do
    resources :contacts, only: [:new, :create, :index] do
      collection do
        get :complete
      end
    end
  end
  namespace :public do
    resources :rooms, only: [:index]
  end
  namespace :public do
    resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end
  namespace :public do
    resources :end_users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get 'posts' => 'end_users#posts', as: 'posts'
      end
      collection do
        get :confirm
      end
      resource:relationships, only:[:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
  	  get 'followers' => 'relationships#followers', as: 'followers'
    end
  end
  namespace :public do
    post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
    get 'homes/about', as: 'about'
  end

  namespace :public do
    get '/search', to: 'searches#search'
  end

  devise_for :end_users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tag_relations, dependent: :destroy
  has_many :posts, through: :post_tag_relations, dependent: :destroy

  validates :name, presence: true
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  def index
    @tag = Tag.new
    @tags = Tag.page(params[:page]).per(10)
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:notice] = "タグを作成しました"
      redirect_to admin_tags_path
    else
      @tags = Tag.page(params[:page]).per(10)
      render :index
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      flash[:notice] = "タグを更新しました"
      redirect_to admin_tags_path
    else
      render :edit
    end
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/edit.html.erb
<div class="container">
  <h4 class="mb-5">タグ編集</h4>
  <%= render 'layouts/error_message', obj: @tag %>
  <div class="mb-5">
    <%= form_with model: @tag, url: admin_tag_path, method: :patch, class: "d-flex" do |f| %>
      <div class="px-3">タグ名</div>
      <div class="px-3"><%= f.text_field :name %></div>
      <div class="px-3"><%= f.submit '変更を保存', class: "btn btn-info btn-sm rounded-pill" %></div>
    <% end %>
    <div class="mt-5 px-3"><%= link_to "一覧に戻る", admin_tags_path %></div>
  </div>
</div>

app/views/admin/tags/index.html.erb
<div class="container">
  <h4 class="mb-5">タグ一覧・追加</h4>
  <%= render 'layouts/error_message', obj: @tag %>
  <div class="mb-5">
    <%= form_with model: @tag, url: admin_tags_path, method: :post, class: "d-flex" do |f| %>
      <div class="px-3">タグ名</div>
      <div class="px-3"><%= f.text_field :name %></div>
      <div class="px-3"><%= f.submit 'タグを作成する', class: "btn btn-success btn-sm rounded-pill" %></div>
    <% end %>
  </div>
  <table class="table">
    <h5>一覧</h5>
    <% @tags.each do |tag| %>
      <tbody>
        <td><%= tag.name %></td>
        <td><%= link_to "編集する", edit_admin_tag_path(tag), class: 'btn btn-sm btn-secondary rounded-pill' %></td>
      </tbody>
    <% end %>
  </table>
  <%= paginate @tags %>
</div>