config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"

  namespace :admin do
    resources :tags, only: [:index, :create, :edit, :update]
  end
  namespace :admin do
    resources :groups, only: [:index, :show, :destroy]
  end
  namespace :admin do
    resources :end_users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get 'posts' => 'end_users#posts', as: 'posts'
      end
    end
  end
  namespace :admin do
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:destroy]
    end
  end
  namespace :admin do
    resources :contacts, only: [:show, :update]
  end
  namespace :admin do
    root to: "homes#top"
  end
  namespace :public do
    resources :groups, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resource :group_users, only: [:create, :destroy]
    end
  end
  namespace :public do
    resources :group_chats, only: [:show, :create]
  end
  namespace :public do
    resources :chats, only: [:show, :create]
  end
  namespace :public do
    resources :contacts, only: [:new, :create, :index] do
      collection do
        get :complete
      end
    end
  end
  namespace :public do
    resources :rooms, only: [:index]
  end
  namespace :public do
    resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end
  namespace :public do
    resources :end_users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get 'posts' => 'end_users#posts', as: 'posts'
      end
      collection do
        get :confirm
      end
      resource:relationships, only:[:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
  	  get 'followers' => 'relationships#followers', as: 'followers'
    end
  end
  namespace :public do
    post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
    get 'homes/about', as: 'about'
  end

  namespace :public do
    get '/search', to: 'searches#search'
  end

  devise_for :end_users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  #自分がフォローされる
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  #自分がフォローする
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :rooms, through: :user_rooms
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users, dependent: :destroy
  has_many :group_chats, dependent: :destroy
  has_many :contacts, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true
  validates :nickname, presence: true
  validates :introduction, presence: true

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io:File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image
  end

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController
  def index
    @end_users = EndUser.page(params[:page]).per(10)
  end

  def show
    @end_user = EndUser.find(params[:id])
  end

  def edit
    @end_user = EndUser.find(params[:id])
  end

  def update
    @end_user = EndUser.find(params[:id])
    if @end_user.update(end_user_params)
      flash[:notice] = "#{@end_user.name}さんのユーザー情報を更新しました"
      redirect_to admin_end_user_path(@end_user)
    else
      render :edit
    end
  end

  def destroy
    @end_user = EndUser.find(params[:id])
    @end_user.destroy
    flash[:notice] = "退会処理を実行致しました"
    redirect_to admin_end_users_path
  end

  def posts
    @end_user = EndUser.find(params[:id])
    @posts = @end_user.posts.order(created_at: :desc).page(params[:page]).per(6)
  end

  private

  def end_user_params
    params.require(:end_user).permit(:profile_image, :name, :nickname, :email, :introduction)
  end

end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/views/admin/end_users/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>名前</th>
      <th>ニックネーム</th>
      <th>自己紹介</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% end_users.each do |end_user| %>
      <tr>
        <td><%= image_tag end_user.get_profile_image, size: "50x50", class: "rounded-circle profile-icon mr-4" %></td>
        <td><%= end_user.name %></td>
        <td><%= end_user.nickname %></td>
        <td><%= end_user.introduction %></td>
        <td><%= link_to 'ユーザーページ', admin_end_user_path(end_user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/end_users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h4 class="mb-5 text-center">会員情報変更</h4>
      <%= render 'layouts/error_message', obj: @end_user %>
      <%= form_with model: @end_user, url: admin_end_user_path(@end_user) do |f| %>
        <div class="field my-4">
          <%= f.label :profile_image, 'プロフィール画像　　　　' %>
          <%= f.file_field :profile_image, placeholder: "Profile Image", accept: "image/*",autocomplete: "profile_image" %>
        </div>
        <div class="field my-4">
          <%= f.label :name, '名前　　　　　　　　　　' %>
          <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
        </div>
        <div class="field my-4">
          <%= f.label :nickname, 'ニックネーム　　　　　　' %>
          <%= f.text_field :nickname, autofocus: true, autocomplete: "nickname" %>
        </div>
        <div class="field my-4">
          <%= f.label :email, 'メールアドレス　　　　　' %>
          <%= f.text_field :email, autofocus: true, autocomplete: "email" %>
        </div>
        <div class="field my-4">
          <%= f.label :introduction, '自己紹介　　　　　　　　' %>
          <%= f.text_area :introduction, autofocus: true, autocomplete: "introduction", class: "mr-3" %>
        </div>
        <div class="actions text-center my-3">
          <%= f.submit "変更する", class: "btn btn-info rounded-pill" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/end_users/index.html.erb
<div class="container">
  <div class="row">
    <%= render "admin/end_users/index", end_users: @end_users %>
  </div>
</div>

app/views/admin/end_users/posts.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h4 class="mb-4 pl-4"><%= @end_user.nickname %> さんの投稿</h4>
      <%= render "admin/posts/index", posts: @posts %>
    </div>
  </div>
  <%= paginate @posts %>
</div>

app/views/admin/end_users/show.html.erb
<div class="container">
  <div class="main-visual col-8 mx-auto">
    <h4 class="py-4 text-center">プロフィール</h4>
    <div class="mb-4 text-center"><%= image_tag @end_user.get_profile_image, size: "140x140",class: "rounded-circle profile-icon" %></div>
    <table class="table">
      <tbody>
        <tr>
          <td><h5>名前</h5></td>
          <td><h5><%= @end_user.name %></h5></td>
        </tr>
        <tr>
          <td><h5>ニックネーム</h5></td>
          <td><h5><%= @end_user.nickname %></h5></td>
        </tr>
        <tr>
          <td><h5>自己紹介</h5></td>
          <td><h5><%= @end_user.introduction %></h5></td>
        </tr>
        <tr>
          <td class="py-4">
            <%= link_to "ユーザー情報を編集する", edit_admin_end_user_path(@end_user), class: "btn btn-info rounded-pill mr-3" %>
            <%= link_to "退会させる", admin_end_user_path(@end_user), method: :delete, "data-confirm" => "本当に退会させますか？", class: "btn btn-danger rounded-pill" %>
          </td>
          <td class="py-4"><%= link_to "投稿を見る", posts_admin_end_user_path(@end_user), class: "btn btn-success rounded-pill float-right" %></td>
        </tr>
      </tbody>
    </table>
    </div>
  </div>
</div>