config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"

  namespace :admin do
    resources :tags, only: [:index, :create, :edit, :update]
  end
  namespace :admin do
    resources :groups, only: [:index, :show, :destroy]
  end
  namespace :admin do
    resources :end_users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get 'posts' => 'end_users#posts', as: 'posts'
      end
    end
  end
  namespace :admin do
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:destroy]
    end
  end
  namespace :admin do
    resources :contacts, only: [:show, :update]
  end
  namespace :admin do
    root to: "homes#top"
  end
  namespace :public do
    resources :groups, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resource :group_users, only: [:create, :destroy]
    end
  end
  namespace :public do
    resources :group_chats, only: [:show, :create]
  end
  namespace :public do
    resources :chats, only: [:show, :create]
  end
  namespace :public do
    resources :contacts, only: [:new, :create, :index] do
      collection do
        get :complete
      end
    end
  end
  namespace :public do
    resources :rooms, only: [:index]
  end
  namespace :public do
    resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end
  namespace :public do
    resources :end_users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get 'posts' => 'end_users#posts', as: 'posts'
      end
      collection do
        get :confirm
      end
      resource:relationships, only:[:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
  	  get 'followers' => 'relationships#followers', as: 'followers'
    end
  end
  namespace :public do
    post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
    get 'homes/about', as: 'about'
  end

  namespace :public do
    get '/search', to: 'searches#search'
  end

  devise_for :end_users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :end_user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :end_user
  belongs_to :post

  validates :comment, presence:true
end

app/models/contact.rb
class Contact < ApplicationRecord
  enum category: {inappropriate_post_end_user:0, consultation_problems:1, others:2}
  enum status: {outstanding:0, processing:1, closed:2}
  belongs_to :end_user
  
  validates :body, presence: true
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  #自分がフォローされる
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  #自分がフォローする
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :rooms, through: :user_rooms
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users, dependent: :destroy
  has_many :group_chats, dependent: :destroy
  has_many :contacts, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true
  validates :nickname, presence: true
  validates :introduction, presence: true

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io:File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image
  end

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :end_user
  belongs_to :post
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :owner, class_name: 'EndUser'
  has_many :group_users
  has_many :end_users, through: :group_users, source: :end_user, dependent: :destroy
  has_many :group_chats, dependent: :destroy

  has_one_attached :image

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-img.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def is_owned_by?(end_user)
    owner.id == end_user.id
  end

  def includesEndUser?(end_user)
    group_users.exists?(end_user_id: end_user.id)
  end

  validates :name, uniqueness: true, presence: true
  validates :introduction, presence: true
end

app/models/group_chat.rb
class GroupChat < ApplicationRecord
  belongs_to :group
  belongs_to :end_user

  validates :message, presence: true, length: {maximum: 140}
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :end_user
  belongs_to :group
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  has_one_attached :video

  has_many :post_tag_relations, dependent: :destroy
  has_many :tags, through: :post_tag_relations, dependent: :destroy
  belongs_to :end_user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, {presence: true, length: {maximum:100}}

  def favorited_by?(end_user)
    favorites.exists?(end_user_id: end_user.id)
  end

  def self.search_for(content)
    Post.where('title LIKE ?', '%'+content+'%')
  end

end

app/models/post_tag_relation.rb
class PostTagRelation < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "EndUser"
  belongs_to :followed, class_name: "EndUser"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :end_users, through: :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tag_relations, dependent: :destroy
  has_many :posts, through: :post_tag_relations, dependent: :destroy

  validates :name, presence: true
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :end_user
  belongs_to :room
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController
  def index
    @groups = Group.page(params[:page]).per(10)
  end

  def show
    @group = Group.find(params[:id])
    @group_chats = @group.group_chats
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    flash[:notice] = "グループを削除しました"
    redirect_to admin_groups_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_end_user!, if: :public_url, except: [:top, :about]
  before_action :authenticate_admin!, if: :admin_url
  def admin_url
    request.fullpath.include?("/admin")
  end

  def public_url
     request.fullpath.include?("/public")
  end
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/groups/_btn.html.erb
<%= link_to "削除", admin_group_path(group), method: :delete,"data-confirm" => "本当に削除しますか？", class: "btn btn-sm btn-danger rounded-pill" %>

app/views/admin/groups/_chat.html.erb
<% chats.each do |chat| %>
  <div class="balloon">
    <div><%= image_tag chat.end_user.get_profile_image, size: "50x50", class: "rounded-circle profile-icon" %></div>
    <div class="message"><p class="float-left"><%= chat.message %></p></div>
  </div>
<% end %>

app/views/admin/groups/index.html.erb
<div class="container">
  <div class="row">
    <h4 class="mb-4">グループ一覧</h4>
    <div class="main-visual col-lg-12 shadow-sm p-5 pb-4 bg-body rounded">
      <table class="table table-hover">
        <thead>
          <tr>
            <th class="col-1"></th>
            <th class="col-2">グループ名</th>
            <th class="col-4">グループ紹介</th>
            <th class="col-2">メンバー</th>
            <th class="col-1"></th>
            <th class="col-2"></th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |group| %>
            <tr class="border-bottom">
              <td class="col-1 align-middle border-left">
                <%= link_to admin_group_path(group) do %>
                  <%= image_tag group.get_image, size: "75x75", class: "rounded-circle group-icon" %>
                <% end %>
              </td>
              <td class="col-2 align-middle border-right"><%= link_to "#{group.name}", public_group_path(group), class: "text-dark" %></td>
              <td class="col-4 align-middle border-right"><%= group.introduction %></td>
              <td class="col-2 align-middle border-right"><%= group.group_users.count %> 人</td>
              <td class="col-1 align-middle border-right text-center">
                <%= link_to admin_group_path(group), class: "door" do %>
                  <i class="fas fa-door-open"></i>
                <% end %>
              </td>
              <td class="col-2 align-middle border-right text-center">
                <%= render "admin/groups/btn", group: group %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/groups/show.html.erb
<div class="container">
  <div class="row pb-3">
    <h4 class="col-6 my-auto">
      <%= image_tag @group.get_image, size: "60x60", class: "rounded-circle group-icon mr-3" %>
      <%= @group.name %>
    </h4>
    <p class="col-6 float-right my-auto">
      <%= render "admin/groups/btn", group: @group %>
    </p>
  </div>
  <div class="row main-visual shadow-sm p-4 pb-4 bg-body rounded d-flex align-items-center">
    <div class="col-2">グループメンバー</div>
    <div class="col-10 d-flex">
      <% @group.end_users.each do |end_user| %>
        <div class="mr-3">
          <%= link_to admin_end_user_path(end_user), class: "text-dark" do %>
            <%= image_tag end_user.get_profile_image, size: "50x50",  class: "rounded-circle profile-icon mr-2" %>
            <%= end_user.nickname %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-10 mx-auto main-visual shadow-sm p-4 pb-4 bg-body rounded">
      <div class="group-chat-message">
        <%= render "admin/groups/chat", chats: @group_chats %>
      </div>
    </div>
  </div>
</div>