config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"

  namespace :admin do
    resources :tags, only: [:index, :create, :edit, :update]
  end
  namespace :admin do
    resources :groups, only: [:index, :show, :destroy]
  end
  namespace :admin do
    resources :end_users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get 'posts' => 'end_users#posts', as: 'posts'
      end
    end
  end
  namespace :admin do
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:destroy]
    end
  end
  namespace :admin do
    resources :contacts, only: [:show, :update]
  end
  namespace :admin do
    root to: "homes#top"
  end
  namespace :public do
    resources :groups, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resource :group_users, only: [:create, :destroy]
    end
  end
  namespace :public do
    resources :group_chats, only: [:show, :create]
  end
  namespace :public do
    resources :chats, only: [:show, :create]
  end
  namespace :public do
    resources :contacts, only: [:new, :create, :index] do
      collection do
        get :complete
      end
    end
  end
  namespace :public do
    resources :rooms, only: [:index]
  end
  namespace :public do
    resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end
  namespace :public do
    resources :end_users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get 'posts' => 'end_users#posts', as: 'posts'
      end
      collection do
        get :confirm
      end
      resource:relationships, only:[:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
  	  get 'followers' => 'relationships#followers', as: 'followers'
    end
  end
  namespace :public do
    post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
    get 'homes/about', as: 'about'
  end

  namespace :public do
    get '/search', to: 'searches#search'
  end

  devise_for :end_users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :end_user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :end_user
  belongs_to :post

  validates :comment, presence:true
end

app/models/contact.rb
class Contact < ApplicationRecord
  enum category: {inappropriate_post_end_user:0, consultation_problems:1, others:2}
  enum status: {outstanding:0, processing:1, closed:2}
  belongs_to :end_user
  
  validates :body, presence: true
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  #自分がフォローされる
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  #自分がフォローする
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :rooms, through: :user_rooms
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users, dependent: :destroy
  has_many :group_chats, dependent: :destroy
  has_many :contacts, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true
  validates :nickname, presence: true
  validates :introduction, presence: true

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io:File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image
  end

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :end_user
  belongs_to :post
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :owner, class_name: 'EndUser'
  has_many :group_users
  has_many :end_users, through: :group_users, source: :end_user, dependent: :destroy
  has_many :group_chats, dependent: :destroy

  has_one_attached :image

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-img.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def is_owned_by?(end_user)
    owner.id == end_user.id
  end

  def includesEndUser?(end_user)
    group_users.exists?(end_user_id: end_user.id)
  end

  validates :name, uniqueness: true, presence: true
  validates :introduction, presence: true
end

app/models/group_chat.rb
class GroupChat < ApplicationRecord
  belongs_to :group
  belongs_to :end_user

  validates :message, presence: true, length: {maximum: 140}
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :end_user
  belongs_to :group
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  has_one_attached :video

  has_many :post_tag_relations, dependent: :destroy
  has_many :tags, through: :post_tag_relations, dependent: :destroy
  belongs_to :end_user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, {presence: true, length: {maximum:100}}

  def favorited_by?(end_user)
    favorites.exists?(end_user_id: end_user.id)
  end

  def self.search_for(content)
    Post.where('title LIKE ?', '%'+content+'%')
  end

end

app/models/post_tag_relation.rb
class PostTagRelation < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "EndUser"
  belongs_to :followed, class_name: "EndUser"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :end_users, through: :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tag_relations, dependent: :destroy
  has_many :posts, through: :post_tag_relations, dependent: :destroy

  validates :name, presence: true
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :end_user
  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_end_user!, if: :public_url, except: [:top, :about]
  before_action :authenticate_admin!, if: :admin_url
  def admin_url
    request.fullpath.include?("/admin")
  end

  def public_url
     request.fullpath.include?("/public")
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error_message.html.erb
<div>
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "") %> 件のエラーが発生しました：</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="p-1 text-center my-auto">
    <%= link_to "お問い合わせ", new_public_contact_path, class: "text-light small border-bottom border-light" %>
    <p class="m-0 small">
      ©BowWow<br>
      愛犬家のためのコミュニティサイト
    </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <nav class="row navbar navbar-expand-lg">
      <%= link_to root_path do %>
        <%= image_tag 'logo.PNG' %>
      <% end %>
      <% flash.each do |message_type, message| %>
      　　<div class="mx-auto my-auto flash alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <ul class="navbar-nav ml-auto">
        <% if end_user_signed_in? %>
        <!--会員ログイン時-->
          <li><%= link_to "マイページ", public_end_user_path(current_end_user.id), class: "btn btn-light rounded-pill mr-3" %></li>
          <li><%= link_to "投稿する", new_public_post_path, class: "btn btn-light rounded-pill" %></li>
          <li><%= link_to "ログアウト", destroy_end_user_session_path, method: :delete, class: "btn btn-link text-dark" %></li>
        <% else %>
        <!--未ログイン時-->
          <li><%= link_to "ログイン", new_end_user_session_path, class: "btn btn-link text-dark mr-2" %></li>
          <li><%= link_to "会員登録", new_end_user_registration_path, class: "btn btn-light rounded-pill mr-3" %></li>
          <li><%= link_to "ゲストログイン", public_homes_guest_sign_in_path, method: :post, class: "btn btn-outline-light rounded-pill" %></li>
        <% end %>
      </ul>
    </nav>
    <nav class="row navbar navbar-expand-lg">
      <ul class="col-12 navbar-nav mx-auto justify-content-between">
        <li>
          <%= link_to root_path, class: "btn btn-light rounded-pill" do %>
            <i class="fas fa-home"></i>
            ホーム
          <% end %>
        </li>
        <li>
          <%= link_to public_posts_path, class: "btn btn-light rounded-pill" do %>
            <i class="fas fa-dog"></i>
            投稿一覧
          <% end %>
        </li>
        <li>
          <%= link_to public_rooms_path, class: "btn btn-light rounded-pill" do %>
            <i class="far fa-comments"></i>
            チャット一覧
          <% end %>
        </li>
        <li>
          <%= link_to public_end_users_path, class: "btn btn-light rounded-pill" do %>
            <i class="fas fa-user"></i>
            会員一覧
          <% end %>
        </li>
        <li>
          <%= link_to public_groups_path, class: "btn btn-light rounded-pill" do %>
            <i class="fas fa-user-friends"></i>
            グループ一覧
          <% end %>
        </li>
        <li><%= render "public/searches/form" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BowWow</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if admin_signed_in? %>
    <!--adminアカウントがログイン時のheader-->
      <%= render 'admin/homes/admin_header' %>
    <% else %>
    <!--ログイン前とend_userログイン時のheader-->
      <%= render 'layouts/header' %>
    <% end %>
    <main class="py-4 mb-auto">
    <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/publics/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/publics/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>